### ISSUE TITLE
Doesn't work in XCode 7

### ISSUE THREAD

**Issue by PaulSlocum** [kitschpatrol/KPRunEverywhereXcodePlugin#10]
Anything I can do to get it working in XCode 7?  I'm on beta 6.

Really great plugin btw, XCode should have it built-in.

**Comment by kitschpatrol** [comment]
Thanks Paul, glad it's helpful.

I'm going to look into Xcode 7 support once it's out of beta. It could be as simple as adding a line to the DVTPlugInCompatibilityUUIDs.

**Comment by zimme** [comment]
Out of beta =)

**Comment by kitschpatrol** [comment]
@zimme Updated but not tested as of 45d600ebfa620cae4a5ac5582ae9a6462bbc3ab8, also threw in the UUID for Xcode 7.1. Let me know if you run into any issues. Thanks!

**Comment by zimme** [comment]
Crashes on Xcode 7

**Comment by PaulSlocum** [comment]
I get that crash in XCode 7 too

**Comment by kitschpatrol** [comment]
Thanks for these reports. I've reproduced the crash locally and hope to have some time to debug this week.

**Comment by deckikwok** [comment]
+1

**Comment by mooshee** [comment]
+1

**Comment by kitschpatrol** [comment]
Please test the latest build in Xcode 7: 4747cbc512efa4d111662b09d61f2a05bb449a60

**Comment by PaulSlocum** [comment]
Works for me in 7.0.  Thanks!!!

**Comment by kitschpatrol** [comment]
Thanks for testing and reporting back.
