### ISSUE TITLE
Support Xcode 8

### ISSUE THREAD

**Issue by dimohamdy** [kitschpatrol/KPRunEverywhereXcodePlugin#17]
can you support Xcode 8 ?

**Comment by kitschpatrol** [comment]
Not sure it's feasible, I haven't had time to investigate yet... but I don't think the new Xcode Source Editor Extensions allow any manipulation beyond text replacement. (For the record, [Apple has removed plugin support as we know it from Xcode 8](https://medium.com/rocknnull/xcode-8-plugins-alcatraz-the-end-of-an-era-ea6e63617d14#.uz0ytufce).)

**Comment by kitschpatrol** [comment]
Have to close this since recent versions of Xcode pulled the rug out from under this type of plugin. An AppleScript approach might be your best bet if you need this functionality in Xcode 8+.
