### ISSUE TITLE
Does not appear to work under Xcode 6.2 and OS X 10.10.2

### ISSUE THREAD

**Issue by FernandoEscher** [kitschpatrol/KPRunEverywhereXcodePlugin#4]
We have used Alcatraz to install the plugin and restarted Xcode.  The plugin is not recognized and no menu options are available.

**Comment by kitschpatrol** [comment]
Hi Fernando, hmm it was working fine on my end as of yesterday on the same 6.2 and 10.10.2 combination.

Have you tried "removing" and then "installing" the PlugIn through Alcatraz, then restarting Xcode?

**Comment by kitschpatrol** [comment]
You're right, needed the new UUID. Just fixed in f784e395c94ae71ed3ce267a6b110196e2acfffd. Thanks!

**Comment by FernandoEscher** [comment]
@kitschpatrol Just tried again and it works now. Thanks for being so quick on the fix!
