### ISSUE TITLE
Need to uninstall / install in Xcode 6.3 after update

### ISSUE THREAD

**Issue by webdevotion** [kitschpatrol/KPRunEverywhereXcodePlugin#6]
to make `KPRunEverywhereXcodePlugin` work again.

**Comment by webdevotion** [comment]
`KPRunEverywhereXcodePlugin` has disappeared for me.  Re-installing does not fix the issue.

**Comment by webdevotion** [comment]
- uninstalled
- quit xcode
- open xcode
- `reload packages` in Alcatraz
- install `KPRunEverywhereXcodePlugin`
- works

**Comment by kitschpatrol** [comment]
@webdevotion thanks for sharing this. I've added another Xcode 6.3 UUID which will should fix this.
