### ISSUE TITLE
Works only when initially installed

### ISSUE THREAD

**Issue by themuser** [kitschpatrol/KPRunEverywhereXcodePlugin#7]
Using 
* Xcode Version 6.3.2 (6D2105)
* Mac OS X 10.10.2 (14C2055)

When I install this plugin from alcatraz, it works very well.

Then I exit teh Xcode and re-run Xcode again, the plugin is gone. I cannot see Run Everywhere option from Product menu.

The only workaround I can do now is just reinstalling this plugin everytime I re-run the xcode.
Any help would be appreciated. Thanks for the awesome plugin.

**Comment by zimme** [comment]
Same problem here.

OS X 10.10.3 (14D136)
Xcode 6.3.2 (6D2105)

**Comment by kitschpatrol** [comment]
Subtle change in 6.3.2 had broken something. A just posted a fix in commit #148e34deb91e0d9e260d5abcaf268cc5dcd2d866. Please uninstall, reinstall, restart Xcode, and be sure you say "Load Bundle" when presented with the following dialogue:

![screen shot 2015-06-16 at 2 59 44 pm](https://cloud.githubusercontent.com/assets/194164/8192251/dfbeb38c-143a-11e5-8f25-065173407db7.png)

Thanks!
