### ISSUE TITLE
Support for Xcode 6.4

### ISSUE THREAD

**Issue by zimme** [kitschpatrol/KPRunEverywhereXcodePlugin#8]

**Comment by kitschpatrol** [comment]
Thanks @zimme! Fixed in 6ef1382e0f3228c80b746c97723252f40fffd3ca. You might have to uninstall the plugin / reinstall the plugin / restart Xcode. Be sure to consent to the "load bundle" after starting up Xcode.

**Comment by zimme** [comment]
:+1:
