### ISSUE TITLE
One stupid little issue with the scheme. (Tested in Xcode 6.3.2)

### ISSUE THREAD

**Issue by azav** [kitschpatrol/KPRunEverywhereXcodePlugin#9]
This will not build unless the scheme is set to Shared.  

Once the scheme is edited and Make Shared is clicked, it builds and installs fine.

Tested on Mac OS 10.10.2, Xcode 6.3.2.

Besides that little issue, it's a dream come true for testing on multiple devices.

**Comment by kitschpatrol** [comment]
Thanks, fixed in d92865adcf98fbf33f1a44a2ff9c587b0d4f7aa0.
